# Generated by Django 4.2.24 on 2025-09-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_auto_20250920_1101"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Cuisine type name (e.g., Italian, Chinese, American)",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="restaurant",
            name="restaurant_cuisine_idx",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="cuisine",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude coordinate", null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisines",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cuisine types associated with this restaurant",
                related_name="restaurants",
                to="restaurants.cuisine",
            ),
        ),
    ]
