# Generated by Django 4.2.24 on 2025-09-21 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "restaurants",
            "0003_cuisine_remove_restaurant_restaurant_cuisine_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRestaurantVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_visit",
                    models.DateField(
                        auto_now=True, help_text="Date of the most recent visit"
                    ),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of visits to this restaurant"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_visits",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_visit", "-visit_count"],
                "indexes": [
                    models.Index(
                        fields=["user", "-visit_count"],
                        name="user_rest_visit_count_idx",
                    ),
                    models.Index(
                        fields=["user", "-last_visit"], name="user_rest_last_visit_idx"
                    ),
                ],
                "unique_together": {("user", "restaurant")},
            },
        ),
        migrations.CreateModel(
            name="UserCuisineStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of visits to restaurants of this cuisine type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cuisine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stats",
                        to="restaurants.cuisine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuisine_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_count"],
                "indexes": [
                    models.Index(
                        fields=["user", "-visit_count"], name="user_cuisine_count_idx"
                    )
                ],
                "unique_together": {("user", "cuisine")},
            },
        ),
    ]
