services:
  backend:
    profiles: 
      - dev
      - prod
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - .:/app  # Only mount code for production
      - lunchlog_logs:/var/log/lunchlog  # Mount logs directory
    ports:
      - "9000:8000"
    depends_on:
      - db
    env_file:
      .env
    command: >
      bash -c "python manage.py migrate &&
               python manage.py create_default_user &&
               gunicorn --bind 0.0.0.0:8000 lunchlog.wsgi:application"
  
  db:
    profiles: 
      - dev
      - prod
    container_name: db
    image: postgres:15
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lunchlog"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    profiles:
      - dev
      - prod
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    profiles:
      - dev
      - prod
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      .env
    command: celery -A lunchlog worker --loglevel=info

  celery-beat:
    profiles:
      - dev
      - prod
    container_name: celery-beat
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      .env
    command: celery -A lunchlog beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  
  

  proxy:
    profiles:
      - prod
    container_name: proxy
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./deploy/certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - backend
    networks:
      - default

volumes:
  postgres_data:  # Database volume
  lunchlog_logs:  # Logs volume
  redis_data:  # Redis data volume