FROM python:3.11-slim

ENV DJANGO_SETTINGS_MODULE=lunchlog.settings.development
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Expose port
EXPOSE 8000

# Command to run the application in development mode
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]