services:
  backend:
    profiles: 
      - dev
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app  # Only mount code for development
    ports:
      - "9000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://lunchlog:lunchlog123@db:5432/lunchlog
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  db:
    profiles: 
      - dev
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_DB: lunchlog
      POSTGRES_USER: lunchlog
      POSTGRES_PASSWORD: lunchlog123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lunchlog"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    profiles:
      - dev
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    profiles:
      - dev
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://lunchlog:lunchlog123@db:5432/lunchlog
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A lunchlog worker --loglevel=info

  celery-beat:
    profiles:
      - dev
    container_name: celery-beat
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://lunchlog:lunchlog123@db:5432/lunchlog
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A lunchlog beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  db_prod:
    profiles: 
      - prod
    container_name: db_prod
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lunchlog"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
  
  backend_prod:
    profiles: 
      - prod
    container_name: backend_prod
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - .:/app  # Only mount code for production
      - lunchlog_logs:/var/log/lunchlog  # Mount logs directory

    depends_on:
      - db_prod
    env_file:
      - .env
    command: >
      bash -c "python manage.py migrate &&
               python manage.py create_default_user &&
               gunicorn --bind 0.0.0.0:8000 lunchlog.wsgi:application"

  proxy:
    profiles:
      - prod
    container_name: proxy
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./deploy/certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - backend_prod
    networks:
      - default

volumes:
  postgres_data:  # Database volume
  lunchlog_logs:  # Logs volume
  redis_data:  # Redis data volume