# Generated by Django 4.2.24 on 2025-09-19 10:42

import apps.receipts.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the purchase")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price of the purchase",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        help_text="Name of the restaurant", max_length=255
                    ),
                ),
                ("address", models.TextField(help_text="Address of the restaurant")),
                (
                    "image",
                    models.ImageField(
                        help_text="Receipt image file",
                        upload_to=apps.receipts.models.receipt_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="receipt_user_date_idx"),
                    models.Index(
                        fields=["user", "-date"], name="receipt_user_date_desc_idx"
                    ),
                ],
            },
        ),
    ]
