# Generated by Django 4.2.24 on 2025-09-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked restaurant from Google Places",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["restaurant"], name="receipt_restaurant_idx"),
        ),
    ]
