# Generated by Django 4.2.24 on 2025-09-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_auto_20250920_1101"),
        ("receipts", "0002_receipt_restaurant_receipt_receipt_restaurant_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="receipt",
            name="receipt_restaurant_idx",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Address of the restaurant",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                help_text="Restaurant associated with this receipt",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="restaurant_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the restaurant",
                max_length=255,
                null=True,
            ),
        ),
    ]
